development:
  sessions:
    default:
      database: ansim_me_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: ansim_me_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
<% if ENV['MONGODB_URL'] %>
production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
<% end %>